package com.example.csit228_f1_v2.SqlSide;

public enum Status {
    LOGIN_SUCCESS, LOGIN_FAILED,
    REGISTRATION_SUCCESS, REGISTRATION_FAILED,
    ACCOUNT_UPDATE_SUCCESS, ACCOUNT_UPDATE_FAILED,
    ACCOUNT_DELETION_SUCCESS, ACCOUNT_DELETION_FAILED,
    NOTE_CREATION_SUCCESS, NOTE_CREATION_FAILED,
    NOTE_UPDATE_SUCCESS, NOTE_UPDATE_FAILED,
    NOTE_DELETION_SUCCESS, NOTE_DELETION_FAILED
}
